### ISSUE TITLE
dependency on typing-extensions

### ISSUE THREAD

**Issue by pfps** [usb-tools/python-hid-parser#15]
hid-parser uses typing-extensions but doesn't require it.
I think that this is only important for Python 3.7.

**Comment by FFY00** [comment]
Yeah, that sounds about right, I haven't touched the code in a little while. Feel free to open a PR removing it on Python >3.7.

**Comment by pfps** [comment]
I think that this has already been done, at least as I now understand how setup.cfg works.  I was only looking in setup.py before

```
[options]
packages = find:
python_requires = >=3.7, <4
install_requires =
    typing-extensions; python_version < '3.8'
```
